# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: pod-config
# data:
#   course: "DevSecOps with AWS"
#   duration: "120hrs"
#   trainer: "kirankumar"
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  course: "DevOps with AWS"
  duration: "120hrs"
  trainer: "kirankumar"